name: Zip Release

on:
  release:
    types: [published]

jobs:
  release:
    name: SmartWater release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Create Zip
        run: |
          cd "${{ github.workspace }}/custom_components/dabpumps"
          zip -r dabpumps.zip ./

      - name: Upload Zip to Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          files: ${{ github.workspace }}/custom_components/dabpumps/dabpumps.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
